# Generated by Django 5.1.1 on 2024-11-11 14:42

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0007_alter_route_end_name_alter_route_start_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesh",
            name="valid_date_end",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 11, 14, 42, 0, 979220, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mesh",
            name="valid_date_start",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 11, 11, 14, 42, 10, 957228, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
