# Generated by Django 5.2.6 on 2025-09-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0014_refactor_mesh_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="route_api.vehicle",
            ),
        ),
    ]
