# Generated by Django 5.1.5 on 2025-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0015_add_vehicle_to_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
