# Generated by Django 5.2.8 on 2025-12-09 16:23

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0016_alter_location_name"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for route categorization",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
