# Generated by Django 5.2.9 on 2025-12-17 15:31

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0017_route_tags"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="tags",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="Tags for route",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
