# Generated by Django 5.2.15 on 2026-06-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0018_alter_route_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="mesh",
            name="protect",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to protect from automated deletion if POLARROUTE_CLEANUP_MESHES is enabled.",
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="protect",
            field=models.BooleanField(
                default=False,
                help_text="Set to True to protect from automated deletion if POLARROUTE_CLEANUP_ROUTES is enabled.",
            ),
        ),
    ]
