# Generated by Django 5.2.1 on 2025-09-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route_api", "0019_alter_location_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="route_api.route",
            ),
        ),
    ]
